/**
 * Invoice memo parsing, building, encoding, and decoding utilities for the AccountingModule.
 *
 * All functions are pure (no side effects, no module state). These utilities
 * operate on two serialization formats:
 *
 * 1. **Transport memo** (`INV:` text format) — carried in `TransferRequest.memo`
 *    via Nostr transport. Human-readable. Secondary/display use only.
 *
 * 2. **On-chain message** (`TransferMessagePayload` JSON bytes) — carried in
 *    `TransferTransactionData.message`. Embedded in the aggregator's Sparse
 *    Merkle Tree and verifiable against its root. Authoritative source.
 *
 * @see ACCOUNTING-SPEC.md §4 — Invoice Reference Encoding
 */

import { SphereError } from '../../core/errors.js';
import type { InvoiceMemoRef, TransferMessagePayload } from './types.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Regex for parsing the transport-layer `INV:` memo format.
 *
 * Captures:
 *   [1] invoice ID — 64 hex characters (case-insensitive)
 *   [2] direction code — `F`, `B`, `RC`, or `RX` (optional; defaults to `F`)
 *   [3] free text — everything after the first space (optional)
 *
 * @see ACCOUNTING-SPEC.md §4.4
 */
export const INVOICE_MEMO_REGEX = /^INV:([0-9a-fA-F]{64})(?::(F|B|RC|RX))?(?: (.+))?$/;

/**
 * Regex for validating a 64-character lowercase/uppercase hex invoice ID.
 * Used by {@link buildInvoiceMemo} before constructing outbound memos.
 */
export const INVOICE_ID_REGEX = /^[0-9a-fA-F]{64}$/;

/**
 * Maps the canonical payment direction name to its wire code.
 *
 * @see ACCOUNTING-SPEC.md §4.2
 */
export const DIRECTION_TO_CODE: Readonly<Record<InvoiceMemoRef['paymentDirection'], 'F' | 'B' | 'RC' | 'RX'>> = {
  forward: 'F',
  back: 'B',
  return_closed: 'RC',
  return_cancelled: 'RX',
} as const;

/**
 * Maps the wire direction code to the canonical payment direction name.
 *
 * @see ACCOUNTING-SPEC.md §4.2
 */
export const CODE_TO_DIRECTION: Readonly<Record<'F' | 'B' | 'RC' | 'RX', InvoiceMemoRef['paymentDirection']>> = {
  F: 'forward',
  B: 'back',
  RC: 'return_closed',
  RX: 'return_cancelled',
} as const;

// ---------------------------------------------------------------------------
// Transport memo utilities
// ---------------------------------------------------------------------------

/**
 * Parses a transport-layer invoice memo string.
 *
 * Format: `INV:{64-hex-id}[:{F|B|RC|RX}][ {freeText}]`
 *
 * The direction code is optional for backward compatibility with pre-module
 * transfers. When absent, direction defaults to `'forward'`. All memos
 * generated by {@link buildInvoiceMemo} always include an explicit direction.
 *
 * Inbound `freeText` is truncated to 1024 Unicode code points to bound index
 * cache and event payload size.
 *
 * @param memo - The raw memo string from `TransferRequest.memo` / `HistoryRecord.memo`.
 * @returns Parsed {@link InvoiceMemoRef} with a lowercase `invoiceId`, or `null`
 *   if the string does not match the `INV:` format.
 *
 * @see ACCOUNTING-SPEC.md §4.5
 *
 * @example
 * ```ts
 * parseInvoiceMemo('INV:abc...64hex...:F hello')
 * // { invoiceId: 'abc...64hex...', paymentDirection: 'forward', freeText: 'hello' }
 *
 * parseInvoiceMemo('not an invoice')
 * // null
 * ```
 */
export function parseInvoiceMemo(memo: string): InvoiceMemoRef | null {
  const match = memo.match(INVOICE_MEMO_REGEX);
  if (!match) return null;

  let paymentDirection: InvoiceMemoRef['paymentDirection'];
  switch (match[2] as 'F' | 'B' | 'RC' | 'RX' | undefined) {
    case 'B':  paymentDirection = 'back'; break;
    case 'RC': paymentDirection = 'return_closed'; break;
    case 'RX': paymentDirection = 'return_cancelled'; break;
    default:   paymentDirection = 'forward'; break; // 'F' or omitted
  }

  // Truncate inbound freeText to 1024 code points. buildInvoiceMemo() caps
  // outbound at 256, but inbound memos from untrusted senders may be
  // arbitrarily long. Truncation bounds index cache and event payload size.
  const rawFreeText = match[3] || undefined;
  const freeText = rawFreeText
    ? [...rawFreeText].slice(0, 1024).join('')
    : undefined;

  return {
    invoiceId: match[1].toLowerCase(),
    paymentDirection,
    freeText,
  };
}

/**
 * Builds an outbound transport-layer invoice memo string.
 *
 * The direction code is always explicit in generated memos. Free text is:
 * - Truncated to 256 Unicode code points (split on code points, not UTF-16
 *   code units, to preserve astral-plane characters such as emoji).
 * - Stripped of all U+0000–U+001F control characters (including `\n` and `\r`).
 *
 * Note: the spec's reference implementation replaces `\r\n` with spaces during
 * memo construction, but this function only strips control characters per the
 * task spec. Callers should not include literal newlines in memo free text
 * intended for single-line display contexts.
 *
 * @param invoiceId - 64-character hex string (case-insensitive; preserved as-is
 *   in the output).
 * @param direction - Wire direction code: `'F'`, `'B'`, `'RC'`, or `'RX'`.
 * @param freeText - Optional human-readable annotation. Sanitized and truncated.
 * @returns The formatted memo string, e.g. `INV:abc...64hex...:F` or
 *   `INV:abc...64hex...:F hello world`.
 *
 * @throws {SphereError} `INVOICE_INVALID_ID` if `invoiceId` is not a 64-char
 *   hex string.
 *
 * @see ACCOUNTING-SPEC.md §4.6
 */
export function buildInvoiceMemo(
  invoiceId: string,
  direction: 'F' | 'B' | 'RC' | 'RX',
  freeText?: string,
): string {
  if (!INVOICE_ID_REGEX.test(invoiceId)) {
    throw new SphereError('Invoice ID must be a 64-char hex string', 'INVOICE_INVALID_ID');
  }

  // Strip ALL control characters U+0000–U+001F (including \n and \r) to ensure
  // the memo is single-line compatible with INVOICE_MEMO_REGEX (.+ does not match \n).
  // Then truncate to 256 Unicode code points (split on code points to handle
  // surrogate pairs for astral-plane characters correctly).
  const sanitized = freeText
    // eslint-disable-next-line no-control-regex -- intentional: strip control chars from untrusted input
    ? [...freeText.replace(/[\x00-\x1f]/g, '')].slice(0, 256).join('').trim()
    : undefined;

  const text = sanitized ? ` ${sanitized}` : '';
  return `INV:${invoiceId}:${direction}${text}`;
}

// ---------------------------------------------------------------------------
// On-chain message encoding/decoding
// ---------------------------------------------------------------------------

/**
 * Decodes raw on-chain `TransferTransactionData.message` bytes into a
 * structured {@link TransferMessagePayload}.
 *
 * Decoding rules (per §4.1):
 * - Null, undefined, or empty input → `null`.
 * - UTF-8 decode → JSON.parse. Any decode/parse failure → `null`.
 * - Non-object result → `null`.
 * - `inv` field validation (strict on id/dir, lenient on ra/ct):
 *   - `id` must be a string of 64 hex chars (normalized to lowercase).
 *   - `dir` must be `'F'`, `'B'`, `'RC'`, or `'RX'`.
 *   - `ra` must be a non-empty string starting with `'DIRECT://'`; stripped
 *     silently if invalid.
 *   - `ct.a` must be a non-empty DIRECT:// address (≤ 256 chars); entire `ct`
 *     stripped silently if invalid.
 *   - `ct.u` must start with `'https://'` or `'wss://'` (≤ 2048 chars, no
 *     control chars); stripped silently (keeping `ct.a`) if invalid.
 * - `txt` field: truncated to 1024 Unicode code points; control chars
 *   U+0000–U+001F except `\n`/`\r` stripped.
 * - If neither a valid `inv` nor a `txt` remain after validation → `null`.
 * - Unknown fields are ignored (forward compatibility).
 *
 * @param messageBytes - Raw bytes from `TransferTransactionData.message`.
 * @returns Validated {@link TransferMessagePayload}, or `null` if absent or
 *   malformed.
 *
 * @see ACCOUNTING-SPEC.md §4.1
 */
export function decodeTransferMessage(messageBytes: Uint8Array | null | undefined): TransferMessagePayload | null {
  if (messageBytes == null || messageBytes.length === 0) return null;

  let parsed: unknown;
  try {
    const text = new TextDecoder().decode(messageBytes);
    parsed = JSON.parse(text);
  } catch {
    return null; // malformed UTF-8 or non-JSON — treat as no invoice reference
  }

  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    return null;
  }

  const raw = parsed as Record<string, unknown>;

  // Validate and sanitize `inv`
  let inv: TransferMessagePayload['inv'] | undefined;
  if (raw['inv'] !== undefined) {
    const rawInv = raw['inv'];

    // Structural guard: must be a non-null, non-array object
    if (typeof rawInv !== 'object' || rawInv === null || Array.isArray(rawInv)) {
      return null;
    }

    const invObj = rawInv as Record<string, unknown>;

    // `id` must be a string; `dir` must be a string if present
    if (
      typeof invObj['id'] !== 'string' ||
      (invObj['dir'] !== undefined && typeof invObj['dir'] !== 'string')
    ) {
      return null; // malformed inv shape — treat as no invoice reference
    }

    // Normalize id to lowercase before validation
    const id = (invObj['id'] as string).toLowerCase();
    if (!/^[0-9a-f]{64}$/.test(id)) {
      return null; // invalid invoice ID format
    }

    const dir = invObj['dir'] as string | undefined;
    if (dir !== undefined && !(['F', 'B', 'RC', 'RX'] as string[]).includes(dir)) {
      return null; // unknown direction code
    }

    // Lenient parsing for `ra` (refund address): include only if valid.
    // Max known DIRECT address is ~75 chars; 256 is a generous upper bound to
    // reject arbitrarily long strings from untrusted on-chain data.
    const rawRa = invObj['ra'];
    const validatedRa: string | undefined =
      typeof rawRa === 'string' &&
      rawRa.startsWith('DIRECT://') &&
      rawRa.length > 'DIRECT://'.length &&
      rawRa.length <= 256
        ? rawRa
        : undefined;

    // Lenient parsing for `ct` (contact): include only if valid
    let validatedCt: NonNullable<NonNullable<TransferMessagePayload['inv']>['ct']> | undefined;
    const rawCt = invObj['ct'];
    if (typeof rawCt === 'object' && rawCt !== null && !Array.isArray(rawCt)) {
      const ctObj = rawCt as Record<string, unknown>;
      const ctA = ctObj['a'];
      if (
        typeof ctA === 'string' &&
        ctA.startsWith('DIRECT://') &&
        ctA.length > 'DIRECT://'.length &&
        ctA.length <= 256
      ) {
        // Lenient parsing for `ct.u`: include only if valid
        const ctU = ctObj['u'];
        const validatedCtU: string | undefined =
          typeof ctU === 'string' &&
          (ctU.startsWith('https://') || ctU.startsWith('wss://')) &&
          ctU.length <= 2048 &&
          // eslint-disable-next-line no-control-regex -- intentional: reject control chars in URL
          !/[\x00-\x1f]/.test(ctU)
            ? ctU
            : undefined;

        validatedCt = {
          a: ctA,
          ...(validatedCtU !== undefined ? { u: validatedCtU } : {}),
        };
      }
      // silently strip malformed contact
    }
    // silently strip if not an object

    // Build the inv object using conditional spreads (all readonly-safe)
    inv = {
      id,
      dir: (dir ?? 'F') as 'F' | 'B' | 'RC' | 'RX',
      ...(validatedRa !== undefined ? { ra: validatedRa } : {}),
      ...(validatedCt !== undefined ? { ct: validatedCt } : {}),
    };
  }

  // Validate and sanitize `txt`
  let txt: string | undefined;
  if (typeof raw['txt'] === 'string') {
    // Truncate to 1024 Unicode code points, strip control chars except \n \r
    // eslint-disable-next-line no-control-regex -- intentional: strip control chars from untrusted input
    const stripped = raw['txt'].replace(/[\x00-\x09\x0b\x0c\x0e-\x1f]/g, '');
    const truncated = [...stripped].slice(0, 1024).join('');
    if (truncated.length > 0) {
      txt = truncated;
    }
  }

  // If neither inv nor txt survived validation, treat as non-invoice transfer
  if (inv === undefined && txt === undefined) {
    return null;
  }

  return {
    ...(inv !== undefined ? { inv } : {}),
    ...(txt !== undefined ? { txt } : {}),
  };
}

/**
 * Encodes a {@link TransferMessagePayload} to UTF-8 JSON bytes for embedding
 * in the `TransferTransactionData.message` field.
 *
 * @param payload - The structured invoice payload to serialize.
 * @returns UTF-8 encoded JSON bytes.
 *
 * @see ACCOUNTING-SPEC.md §4.1
 */
export function encodeTransferMessage(payload: TransferMessagePayload): Uint8Array {
  return new TextEncoder().encode(JSON.stringify(payload));
}

// ---------------------------------------------------------------------------
// PaymentsModule integration helper
// ---------------------------------------------------------------------------

/**
 * Converts a transport-layer `INV:` memo string into on-chain message bytes.
 *
 * This helper is used by `PaymentsModule.send()` (and split executor paths)
 * to encode invoice references from the Nostr memo into the structured
 * `TransferTransactionData.message` field. Non-invoice memos return `null`
 * so that private user text is never written to the permanent on-chain record.
 *
 * Steps:
 * 1. If `memo` is absent or does not match the `INV:` format → return `null`.
 * 2. Build a {@link TransferMessagePayload} from the parsed reference:
 *    - `inv.id` = normalized `invoiceId`
 *    - `inv.dir` = direction code mapped from `paymentDirection`
 *    - `inv.ra` = `refundAddress` if provided
 *    - `inv.ct` = `{ a: contact.address, u?: contact.url }` if provided
 *    - `txt` = `freeText` if present
 * 3. Encode and return the payload bytes.
 *
 * @param memo - Transport memo string (e.g. `INV:abc...:F hello`). May be
 *   `undefined` for transfers without a memo.
 * @param refundAddress - Optional DIRECT:// address for auto-return routing.
 *   Embedded in `inv.ra` on-chain; NOT included in the transport memo (privacy).
 * @param contact - Optional contact info for the payer. Embedded in `inv.ct`
 *   on-chain; NOT included in the transport memo (privacy).
 * @returns UTF-8 JSON bytes for the on-chain message, or `null` if the memo
 *   is absent or non-invoice.
 *
 * @see ACCOUNTING-SPEC.md §4.7
 */
export function parseInvoiceMemoForOnChain(
  memo: string | undefined,
  refundAddress?: string,
  contact?: { address: string; url?: string },
): Uint8Array | null {
  if (!memo) return null;

  const ref = parseInvoiceMemo(memo);
  if (!ref) {
    // Non-invoice memo: keep transport-only to preserve privacy
    return null;
  }

  // Validate refundAddress before embedding on-chain (same rules as decodeTransferMessage)
  const validRefundAddress =
    refundAddress &&
    typeof refundAddress === 'string' &&
    refundAddress.startsWith('DIRECT://') &&
    refundAddress.length > 9 &&
    refundAddress.length <= 256
      ? refundAddress
      : undefined;

  // Validate contact fields before embedding on-chain (same rules as decodeTransferMessage)
  let validContact: { a: string; u?: string } | undefined;
  if (contact) {
    const validAddr =
      typeof contact.address === 'string' &&
      contact.address.startsWith('DIRECT://') &&
      contact.address.length > 9 &&
      contact.address.length <= 256;

    if (validAddr) {
      validContact = { a: contact.address };
      if (
        contact.url &&
        typeof contact.url === 'string' &&
        (contact.url.startsWith('https://') || contact.url.startsWith('wss://')) &&
        contact.url.length <= 2048 &&
        // eslint-disable-next-line no-control-regex -- intentional: reject control chars in URL
        !/[\x00-\x1f]/.test(contact.url)
      ) {
        validContact.u = contact.url;
      }
    }
  }

  const inv: NonNullable<TransferMessagePayload['inv']> = {
    id: ref.invoiceId,
    dir: DIRECTION_TO_CODE[ref.paymentDirection],
    ...(validRefundAddress ? { ra: validRefundAddress } : {}),
    ...(validContact ? { ct: validContact } : {}),
  };

  const payload: TransferMessagePayload = {
    inv,
    ...(ref.freeText ? { txt: ref.freeText } : {}),
  };

  return encodeTransferMessage(payload);
}
